name: food_analysis
channels:
  - defaults
dependencies:
  - aom=3.12.1
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - eigen=5.0.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gflags=2.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif=1.3.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.33.0
  - libsodium=1.0.20
  - libtheora=1.2.0
  - libtiff=4.7.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nest-asyncio=1.6.0
  - numba=0.60.0
  - numexpr=2.11.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.12.0
  - openjpeg=2.5.4
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - umap-learn=0.5.4
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
prefix: C:\Users\super\anaconda3\envs\food_analysis
